Document: mc
Title: Debian mc Manual
Author: <insert document author here>
Abstract: This manual describes what mc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mc/mc.sgml.gz

Format: postscript
Files: /usr/share/doc/mc/mc.ps.gz

Format: text
Files: /usr/share/doc/mc/mc.text.gz

Format: HTML
Index: /usr/share/doc/mc/html/index.html
Files: /usr/share/doc/mc/html/*.html
